--CREATE DATABASE SE1706_SWP391_Group6
--DROP DATABASE SE1706_SWP391_Group6
USE SE1706_SWP391_Group6

CREATE TABLE [Role] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[role] NVARCHAR(50) NOT NULL,
PRIMARY KEY ([id]),
)

CREATE TABLE [Admin] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[roleId] BIGINT NOT NULL,
[firstName] NVARCHAR(50) NOT NULL,
[lastName] NVARCHAR(50) NOT NULL,
[mobile] NVARCHAR(15) NOT NULL,
[email] NVARCHAR(50) NOT NULL,
[passwordHash] NVARCHAR(32) NOT NULL,
[image] NVARCHAR(MAX) NULL DEFAULT NULL,
[lastLogin] DATETIME NULL DEFAULT NULL,
[lastLogout] DATETIME NULL DEFAULT NULL,
PRIMARY KEY ([id]),
FOREIGN KEY ([roleId]) REFERENCES [Role](id)
)

CREATE TABLE [User] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[firstName] NVARCHAR(50) NULL DEFAULT NULL,
[lastName] NVARCHAR(50) NULL DEFAULT NULL,
[dob]  DATETIME NULL DEFAULT NULL,
[mobile] NVARCHAR(15) NULL DEFAULT NULL,
[email] NVARCHAR(50) NULL DEFAULT NULL,
[passwordHash] NVARCHAR(32) NOT NULL,
[registerAt] DATETIME NOT NULL,
[lastLogin] DATETIME NULL DEFAULT NULL,
[lastLogout] DATETIME NULL DEFAULT NULL,
PRIMARY KEY ([id])
)

CREATE TABLE [Country] (
[id] INT NOT NULL IDENTITY(1,1),
[name] NVARCHAR(50) NOT NULL,
[tax] FLOAT DEFAULT 0,
[shipping] FLOAT DEFAULT 0,
PRIMARY KEY ([id]),
)

CREATE TABLE [Category] (
[id] INT NOT NULL IDENTITY(1,1),
[name] NVARCHAR(75) NOT NULL, 
[description] NVARCHAR(MAX) NULL,
PRIMARY KEY ([id]),
)

CREATE TABLE [Product] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[model] NVARCHAR(50) NULL DEFAULT NULL,
[categoryId] INT DEFAULT 0,
[name] NVARCHAR(75) NOT NULL,
[description] NVARCHAR(MAX) NULL DEFAULT NULL,
[sellPrice] FLOAT DEFAULT 0,
[warranty] SMALLINT DEFAULT 0,
[sold] BIGINT DEFAULT 0,
[view] BIGINT DEFAULT 0,
[manufacturer] NVARCHAR(50) NULL DEFAULT NULL, 
[createdAt] DATETIME NOT NULL,
[updatedAt] DATETIME NULL DEFAULT NULL,
PRIMARY KEY ([id]),
FOREIGN KEY ([categoryId]) REFERENCES [Category](id)
)

CREATE TABLE [ProductImage] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[productId] BIGINT NOT NULL,
[alt] NVARCHAR(100) NULL DEFAULT NULL,
[source] NVARCHAR(MAX) NULL DEFAULT NULL,
PRIMARY KEY ([id]),
FOREIGN KEY ([productId]) REFERENCES [Product](id),
)

CREATE TABLE [ProductComment] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[productId] BIGINT NOT NULL,
[userId] BIGINT NULL DEFAULT NULL,
[name] NVARCHAR(100) NULL DEFAULT NULL,
[email] NVARCHAR(100) NULL DEFAULT NULL,
[title] NVARCHAR(100) NULL DEFAULT NULL,
[rating] TINYINT NOT NULL DEFAULT 0,
[image] NVARCHAR(MAX) NULL DEFAULT NULL,
[createdAt] DATETIME NOT NULL,
[updatedAt] DATETIME NULL DEFAULT NULL,
[content] NVARCHAR(MAX) NULL DEFAULT NULL,
PRIMARY KEY ([id]),
FOREIGN KEY ([productId]) REFERENCES [Product](id),
)

CREATE TABLE [Discount] (
[code] VARCHAR(15) NOT NULL,
[name] NVARCHAR(50) NULL DEFAULT NULL,
[amount] FLOAT NOT NULL DEFAULT 0, 
[description] NVARCHAR(MAX) NULL DEFAULT NULL,
[type] NVARCHAR(20) NULL DEFAULT NULL,
[status] NVARCHAR(20) DEFAULT 'inactivated',
PRIMARY KEY ([code])
)

CREATE TABLE [user_discount] (
[userId] BIGINT NOT NULL,
[discountCode] VARCHAR(15) NOT NULL,
[number] TINYINT DEFAULT 1,
PRIMARY KEY ([userId],[discountCode]),
FOREIGN KEY ([userId]) REFERENCES [User](id),
FOREIGN KEY ([discountCode]) REFERENCES [Discount](code)
)

CREATE TABLE [product_discount] (
[productId] BIGINT NOT NULL,
[discountCode] VARCHAR(15) NOT NULL,
[fromDate] DATETIME NULL DEFAULT NULL,
[toDate] DATETIME NULL DEFAULT NULL,
PRIMARY KEY ([productId],[discountCode]),
FOREIGN KEY ([productId]) REFERENCES [Product](id),
FOREIGN KEY ([discountCode]) REFERENCES [Discount](code)
)

CREATE TABLE [Status] (
[id] TINYINT NOT NULL,
[name] NVARCHAR(50) NOT NULL,
[content] NVARCHAR(MAX) NULL DEFAULT NULL,
PRIMARY KEY ([id]),
)

CREATE TABLE [Order] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[userId] BIGINT NOT NULL,
[firstName] NVARCHAR(50) NULL DEFAULT NULL,
[lastName] NVARCHAR(50) NULL DEFAULT NULL,
[mobile] NVARCHAR(15) NULL DEFAULT NULL,
[statusId] TINYINT NOT NULL DEFAULT 0,
[discountCode] VARCHAR(15) NULL DEFAULT NULL,
[subTotal] FLOAT NOT NULL DEFAULT 0,
[grandTotal] FLOAT NOT NULL DEFAULT 0,
[line1] NVARCHAR(50) NULL DEFAULT NULL,
[line2] NVARCHAR(50) NULL DEFAULT NULL,
[city] NVARCHAR(50) NULL DEFAULT NULL,
[province] NVARCHAR(50) NULL DEFAULT NULL,
[countryId] INT NULL DEFAULT NULL,
[createdAt] DATETIME NULL DEFAULT NULL,
[updatedAt] DATETIME NULL DEFAULT NULL,
[content] NVARCHAR(MAX) NULL DEFAULT NULL,
[payment] NVARCHAR(50) NULL DEFAULT NULL,
PRIMARY KEY ([id]),
FOREIGN KEY ([userId]) REFERENCES [User](id),
FOREIGN KEY ([statusId]) REFERENCES [Status](id),
FOREIGN KEY ([countryId]) REFERENCES [Country](id),
FOREIGN KEY ([discountCode]) REFERENCES [Discount](code)
)

CREATE TABLE [OrderItem] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[productId] BIGINT NOT NULL,
[orderId] BIGINT NOT NULL,
[quantity] INT NOT NULL DEFAULT 0,
[content] NVARCHAR(MAX) NULL DEFAULT NULL,
PRIMARY KEY ([id]),
FOREIGN KEY ([productId]) REFERENCES [Product](id),
FOREIGN KEY ([orderId]) REFERENCES [Order](id)
)

CREATE TABLE [ProductInStock] (
[serial] NVARCHAR(50) NOT NULL,
[productId] BIGINT NOT NULL,
[orderItemId] BIGINT NUll DEFAULT NULL,
[mfgDate] DATETIME NULL DEFAULT NULL,
[warrantyExp] DATETIME NULL DEFAULT NULL,
PRIMARY KEY ([serial]), 
FOREIGN KEY ([productId]) REFERENCES [Product](id),
FOREIGN KEY ([orderItemId]) REFERENCES [OrderItem](id)
)

CREATE TABLE [NewsGroup] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[name] NVARCHAR(75) NULL DEFAULT NULL,
[type] NVARCHAR(75) NULL DEFAULT NULL,
PRIMARY KEY ([id]),
)

CREATE TABLE [News] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[adminId] BIGINT NULL DEFAULT NULL,
[groupId] BIGINT NOT NULL,
[title] NVARCHAR(100) NULL DEFAULT NULL,
[heading] NVARCHAR(MAX) NULL DEFAULT NULL,
[author] NVARCHAR(50) NULL DEFAULT NULL,
[image] NVARCHAR(MAX) NULL DEFAULT NULL,
[view] BIGINT DEFAULT 0,
[STT] BIGINT NULL DEFAULT NULL,
[link] NVARCHAR(MAX) NULL DEFAULT NULL,
[createdAt] DATETIME NULL DEFAULT NULL,
[updatedAt] DATETIME NULL DEFAULT NULL,
[content] NVARCHAR(MAX) NULL DEFAULT NULL,
PRIMARY KEY ([id]),
FOREIGN KEY ([groupId]) REFERENCES [NewsGroup](id),
FOREIGN KEY ([adminId]) REFERENCES [Admin](id),
)

CREATE TABLE [Service] (
[code] NVARCHAR(20) NOT NULL,
[type] NVARCHAR(75) NULL DEFAULT NULL,
[name] NVARCHAR(75) NULL DEFAULT NULL,
[amount] TINYINT DEFAULT 0,
[price] FLOAT DEFAULT 0,
[status] NVARCHAR(20) DEFAULT 'inactivated',
[content] NVARCHAR(MAX) NULL DEFAULT NULL,
[createdAt] DATETIME NULL DEFAULT NULL,
[updatedAt] DATETIME NULL DEFAULT NULL,
PRIMARY KEY ([code])
)

CREATE TABLE [product_service] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[code] NVARCHAR(20) NOT NULL,
[serial] NVARCHAR(50) NOT NULL,
[firstName] NVARCHAR(50) NULL DEFAULT NULL,
[lastName] NVARCHAR(50) NULL DEFAULT NULL,
[mobile] NVARCHAR(15) NULL DEFAULT NULL,
[total] FLOAT NOT NULL DEFAULT 0,
[line1] NVARCHAR(50) NULL DEFAULT NULL,
[line2] NVARCHAR(50) NULL DEFAULT NULL,
[city] NVARCHAR(50) NULL DEFAULT NULL,
[province] NVARCHAR(50) NULL DEFAULT NULL,
[countryId] INT NULL DEFAULT NULL,
[createdAt] DATETIME NULL DEFAULT NULL,
[content] NVARCHAR(MAX) NULL DEFAULT NULL,
[statusId] TINYINT NOT NULL DEFAULT 0,
[startAt] DATETIME NULL DEFAULT NULL,
[endAt] DATETIME NULL DEFAULT NULL,
FOREIGN KEY ([code]) REFERENCES [Service](code),
FOREIGN KEY ([serial]) REFERENCES [ProductInStock](serial),
PRIMARY KEY ([id])
)
