--CREATE DATABASE SE1706_SWP391_Group6
--DROP DATABASE SE1706_SWP391_Group6
--USE SE1706_SWP391_Group6

CREATE TABLE [User] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[firstName] NVARCHAR(50) NOT NULL,
[lastName] NVARCHAR(50) NOT NULL,
[mobile] NVARCHAR(15) NOT NULL,
[email] NVARCHAR(50) NOT NULL,
[passwordHash] NVARCHAR(32) NOT NULL,
[image] TEXT NULL,
[registerAt] DATETIME NOT NULL,
[lastLogin] DATETIME NULL DEFAULT NULL,
PRIMARY KEY ([id]),
UNIQUE ([mobile]),
UNIQUE ([email])
)

CREATE TABLE [Admin] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[firstName] NVARCHAR(50) NOT NULL,
[lastName] NVARCHAR(50) NOT NULL,
[mobile] NVARCHAR(15) NOT NULL,
[email] NVARCHAR(50) NOT NULL,
[passwordHash] NVARCHAR(32) NOT NULL,
[registerAt] DATETIME NOT NULL,
[lastLogin] DATETIME NULL DEFAULT NULL,
PRIMARY KEY ([id]),
UNIQUE ([mobile]),
UNIQUE ([email])
)

CREATE TABLE [Category] (
[id] INT NOT NULL IDENTITY(1,1),
[name] NVARCHAR(75) NOT NULL, 
[description] TEXT NULL,
PRIMARY KEY ([id]),
UNIQUE ([name])
)

CREATE TABLE [Product] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[userId] BIGINT NOT NULL,
[categoryId] INT NOT NULL DEFAULT 0,
[name] NVARCHAR(75) NOT NULL,
[description] TEXT NULL,
[image] TEXT NULL,
[sellPrice] FLOAT NOT NULL DEFAULT 0,
[discount] FLOAT NOT NULL DEFAULT 0,
[quantity] BIGINT NOT NULL DEFAULT 0,
[madeIn] NVARCHAR(50) NULL DEFAULT NULL,
[manufacturer] NVARCHAR(50) NULL DEFAULT NULL, 
[createAt] DATETIME NOT NULL,
[updateAt] DATETIME NULL DEFAULT NULL,
PRIMARY KEY ([id]),
FOREIGN KEY ([userId]) REFERENCES [User](id),
FOREIGN KEY ([categoryId]) REFERENCES [Category](id)
)

CREATE TABLE [ProductInStock] (
[serial] NVARCHAR(10) NOT NULL,
[productId] BIGINT NOT NULL,
[mfgDate] DATETIME NOT NULL,
[warranty] SMALLINT NULL DEFAULT 0,
[warrantyExp] DATETIME NULL DEFAULT NULL,
[color] NVARCHAR(30) NULL DEFAULT NULL,
PRIMARY KEY ([serial]), 
FOREIGN KEY ([productId]) REFERENCES [Product](id)
)

CREATE TABLE [ProductComment] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[productId] BIGINT NOT NULL,
[title] NVARCHAR(100) NOT NULL,
[rating] TINYINT NOT NULL DEFAULT 0,
[image] TEXT NULL,
[createdAt] DATETIME NOT NULL,
[updatedAt] DATETIME NULL DEFAULT NULL,
[content] TEXT NULL DEFAULT NULL,
PRIMARY KEY ([id]),
FOREIGN KEY ([productId]) REFERENCES [Product](id),
)

CREATE TABLE [Order] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[userId] BIGINT NOT NULL,
[status] TINYINT NOT NULL DEFAULT 0,
[subTotal] FLOAT NOT NULL DEFAULT 0,
[itemDiscount] FLOAT NOT NULL DEFAULT 0,
[tax] FLOAT NOT NULL DEFAULT 0,
[shipping] FLOAT NOT NULL DEFAULT 0,
[total] FLOAT NOT NULL DEFAULT 0,
[promo] NVARCHAR(50) NULL DEFAULT NULL,
[discount] FLOAT NOT NULL DEFAULT 0,
[grandTotal] FLOAT NOT NULL DEFAULT 0,
[line1] NVARCHAR(50) NULL DEFAULT NULL,
[line2] NVARCHAR(50) NULL DEFAULT NULL,
[city] NVARCHAR(50) NULL DEFAULT NULL,
[province] NVARCHAR(50) NULL DEFAULT NULL,
[country] NVARCHAR(50) NULL DEFAULT NULL,
[createdAt] DATETIME NOT NULL,
[updatedAt] DATETIME NULL DEFAULT NULL,
[content] TEXT NULL DEFAULT NULL,
PRIMARY KEY ([id]),
FOREIGN KEY ([userId]) REFERENCES [User](id)
)

CREATE TABLE [OrderItem] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[productId] BIGINT NOT NULL,
[orderId] BIGINT NOT NULL,
[quantity] INT NOT NULL DEFAULT 0,
[createdAt] DATETIME NOT NULL,
[updatedAt] DATETIME NULL DEFAULT NULL,
[content] TEXT NULL DEFAULT NULL,
PRIMARY KEY ([id]),
FOREIGN KEY ([productId]) REFERENCES [Product](id),
FOREIGN KEY ([orderId]) REFERENCES [Order](id)
)

CREATE TABLE [NewsGroup] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[name] NVARCHAR(75) NOT NULL,
PRIMARY KEY ([id]),
)

CREATE TABLE [News] (
[id] BIGINT NOT NULL IDENTITY(1,1),
[groupId] BIGINT NOT NULL,
[title] NVARCHAR(100) NOT NULL,
[heading] NVARCHAR(MAX) NULL DEFAULT NULL,
[image] TEXT NULL,
[createdAt] DATETIME NOT NULL,
[updatedAt] DATETIME NULL DEFAULT NULL,
[content] TEXT NULL DEFAULT NULL,
PRIMARY KEY ([id]),
FOREIGN KEY ([groupId]) REFERENCES [NewsGroup](id),
)